### ISSUE TITLE
Local workspace file ('angular.json') could not be found.

### ISSUE THREAD

**Issue by JonasJW** [sebawita/pet-bros#6]
Hey,

When I try do do `ng serve` I get the error `Local workspace file ('angular.json') could not be found.` This might have to do with different angular versions but I don't know. Do you have a Idea?

**Comment by JonasJW** [comment]
Sorry, didn't know there was a newer version: https://github.com/sebawita/pet-bros-lite

**Comment by kedhas** [comment]
Did u check if the files 'angular.json' actually exists ?
